name: Build & Publish wheel

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependency
      run: |
        pip install cython
    - name: Building wheel
      run: |
        make wheel_manylinux
    - name: Copy wheels in dist
      run: cp wheelhouse*/fastrlock*.whl dist/
    - name: Push build artifacts to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
